# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actionns/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        pip install flask
    - run:  sudo systemctl daemon-reload
    - name: deploy changed file
      run: |
        sudo systemctl stop pythonapp.service
        cp ${{github.workspace}}/application.py /home/gheactionsuser/pythonapp
        sudo systemctl start pythonapp.service

